name: Automation jobs

on:
  workflow_dispatch: 
    inputs:
      tag:
        description: Tag Name
        default: Teju the princess
        required: true
        type: string
      build:
        description: build name
        default: 1.41.7
        required: false
        type: environment
      run:
        description: Failed Run
        type: boolean
        default: true
        required: true
    
  
